### ISSUE TITLE
Make helloworld test project

### ISSUE THREAD

**Issue by andreacicovic** [joshakbar14/Smart-ParkingLot#5]
- [x] #6
- [x] #7
- [x] #8

**Comment by JaiminD99** [comment]
- [ ] Upload on RPI

**Comment by irbahanifah** [comment]
///Blinking the LED in raspberry pi

#include <csignal>
#include <iostream>
#include <pigpio.h>
const int RedLED = 21;
volatile sig_atomic_t signal_received = 0;
void sigint_handler(int signal) {
   signal_received = signal;
}
int main() {
   if (gpioInitialise() == PI_INIT_FAILED) {
      std::cout << "ERROR: Failed to initialize the GPIO interface." << std::endl;
      return 1;
   }
   gpioSetMode(RedLED, PI_OUTPUT);
   signal(SIGINT, sigint_handler);
   std::cout << "Press CTRL-C to exit." << std::endl;
   while (!signal_received) {
      gpioWrite(RedLED, PI_HIGH);
      time_sleep(1);
      gpioWrite(RedLED, PI_LOW);
      time_sleep(1);
   }
   gpioSetMode(RedLED, PI_INPUT);
   gpioTerminate();
   std::cout << std::endl;
   return 0;
}

**Comment by irbahanifah** [comment]
//BLINKING THE LED//
//TO TEST RASPBERRY PI//

#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include <fcntl.h>

class LinuxFile
{
private:
    int m_Handle;

public:
    LinuxFile(const char *pFile, int flags = O_RDWR)
    {
        m_Handle = open(pFile, flags);
    }

    ~LinuxFile()
    {
        if (m_Handle != -1)
            close(m_Handle);
    }

    size_t Write(const void *pBuffer, size_t size)
    {
        return write(m_Handle, pBuffer, size);
    }

    size_t Read(void *pBuffer, size_t size)
    {
        return read(m_Handle, pBuffer, size);
    }

    size_t Write(const char *pText)
    {
        return Write(pText, strlen(pText));
    }

    size_t Write(int number)
    {
        char szNum[32];
        snprintf(szNum, sizeof(szNum), "%d", number);
        return Write(szNum);
    }
};

class LinuxGPIOExporter
{
protected:
    int m_Number;

public:
    LinuxGPIOExporter(int number)
            : m_Number(number)
    {
        LinuxFile("/sys/class/gpio/export", O_WRONLY).Write(number);
    }

    ~LinuxGPIOExporter()
    {
        LinuxFile("/sys/class/gpio/unexport", O_WRONLY).Write(m_Number);
    }
};

class LinuxGPIO : public LinuxGPIOExporter
{
public:
    LinuxGPIO(int number)
            : LinuxGPIOExporter(number)
    {
    }

    void SetValue(bool value)
    {
        char szFN[128];
        snprintf(szFN, sizeof(szFN), "/sys/class/gpio/gpio%d/value", m_Number);
        LinuxFile(szFN).Write(value ? "1" : "0");
    }

    void SetDirection(bool isOutput)
    {
        char szFN[128];
        snprintf(szFN, sizeof(szFN),
                 "/sys/class/gpio/gpio%d/direction", m_Number);
        LinuxFile(szFN).Write(isOutput ? "out" : "in");
    }
};

int main(int argc, char *argv[])
{
    LinuxGPIO gpio27(27);
    gpio27.SetDirection(true);
    bool on = true;
    for (;;)
    {
        printf("Switching %s the LED...\n", on ? "on" : "off");
        gpio27.SetValue(on);
        on = !on;
        sleep(1);
    }
}
